# Numpy 
- a general purpose array-processing package
- provides high-performance multi-d array objects and tools for working with these arrays
# Array
- stores values of same data type
- the reason we will be converting our dataset into an array after feature engineering is because array operations are very fast and model gets trained faster

In [ ]:
# if you are not using Jupyter nb and installed python manually, type the following in your command prompt

# pip install numpy

# for conda pyramid:

# conda install numpy

In [1]:
# importing numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [6]:
type(arr)

# press shift + tab before the starting bracket to know more about inbuilt methods

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.shape

(5,)

In [30]:
# Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[6,7,8,9,10]
my_lst3=[11,12,13,14,15]

arr=np.array([my_lst1, my_lst2, my_lst3])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
arr.shape

(3, 5)

In [32]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [33]:
arr.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [34]:
arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [35]:
arr.shape # remains unchanged unless you assign it back to itself

(3, 5)

### Indexing

In [36]:
# Accessing the array elements

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
arr[2]

array([11, 12, 13, 14, 15])

In [38]:
arr[2][2]

13

In [39]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [41]:
arr[0:2,0:2]

# or arr[:2,:2]

array([[1, 2],
       [6, 7]])

In [43]:
arr[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [49]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [51]:
arr=np.arange(0,10)

# creates a 1-D array and takes a range bw start and stop
# step is an optional parameter

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr=np.arange(0,10,2)

arr

array([0, 2, 4, 6, 8])

In [57]:
# or

arr=np.arange(start=0, stop=10, step=2)

arr

array([0, 2, 4, 6, 8])

In [59]:
np.linspace(0, 10, 20) # returns evenly spaced numbers over a specified interval

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [60]:
# or

np.linspace(start=0, stop=10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [86]:
# Copy function

arr1=[1,2,3,4,5,6,7,8,9,10]

arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [87]:
for i in range(3, len(arr1)):
    arr1[i] = 100

arr1

[1, 2, 3, 100, 100, 100, 100, 100, 100, 100]

In [88]:
arr2=arr1.copy()

# an independent copy of arr 1 with different memory space gets created

In [91]:
for i in range(3, len(arr2)):
    arr2[i] = 200

arr2

[1, 2, 3, 200, 200, 200, 200, 200, 200, 200]

In [98]:
arr1 

[1, 2, 3, 200, 200, 200, 200, 200, 200, 200]

There is no effect of arr2 on arr1.

In [93]:
# normal assignment

arr1=[1,2,3,4,5,6,7,8,9,10]

arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [94]:
for i in range(3, len(arr1)):
    arr1[i] = 100

arr1

[1, 2, 3, 100, 100, 100, 100, 100, 100, 100]

In [95]:
arr2=arr1 # arr1 and arr2 share same memory now

In [96]:
for i in range(3, len(arr2)):
    arr2[i] = 200

arr2

[1, 2, 3, 200, 200, 200, 200, 200, 200, 200]

In [97]:
arr1

[1, 2, 3, 200, 200, 200, 200, 200, 200, 200]

When we changes arr2, similar changes in arr1 occur.

### useful for EDA

In [104]:
# Creating an array of 1s

np.ones(4)

array([1., 1., 1., 1.])

In [105]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [106]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [107]:
# Random distribution

np.random.rand(3,3)

# Create an array of the given shape with random numbers bw [0, 1)

array([[0.03563037, 0.51207296, 0.58049799],
       [0.59512427, 0.18335989, 0.91629782],
       [0.16291362, 0.82527137, 0.40212368]])

In [110]:
np.random.rand()

# generates a single random no. bw [0,1)

0.8048850457957283

In [112]:
arr_ex=np.random.randn(4,4)

# Return a sample (or samples) from the "standard normal" distribution.

#The standard normal distribution is symmetric around its mean of zero and has a bell-shaped curve. It is characterized by the properties that approximately 68% of the data falls within one standard deviation of the mean, 95% falls within two standard deviations, and about 99.7% falls within three standard deviations.arr_ex

array([[ 1.06956372,  0.88147445, -1.33760921, -0.40008483],
       [ 0.15548013, -0.60209109,  0.13463945,  0.75027404],
       [-1.11102281, -0.52605237,  0.74195444, -0.84228238],
       [-1.15902703, -1.81251264, -0.70461117, -1.02734397]])

In [119]:
np.random.randint(0,100)

# gives a random integer bw 0 & 100

47

In [118]:
np.random.randint(0, 100, 8)

# gives an array 8 random integers bw 0 & 100

array([54, 75, 23, 76, 10, 97, 59, 78])

In [114]:
np.random.randint(0, 100, 8).reshape(4,2)

array([[78, 73],
       [69, 26],
       [60, 68],
       [31, 90]])

In [122]:
np.random.random_sample()

# Return random floats in the half-open interval [0.0, 1.0).

0.24579523337747677

In [128]:
np.random.random_sample((2))

# Return an array of 2 random floats in the half-open interval [0.0, 1.0).

array([0.93070316])

In [123]:
np.random.random_sample((1,5))

# 5*1 samples drawn

array([[0.53611061, 0.35000365, 0.24775714, 0.74684742, 0.40509847]])

In [124]:
np.random.random_sample((1,5,4))

# 5*1*4 samples drawn

array([[[0.84927835, 0.87338307, 0.67128909, 0.73965457],
        [0.11081011, 0.52657797, 0.13918313, 0.78478671],
        [0.32562461, 0.43173837, 0.97139019, 0.33548573],
        [0.14687856, 0.8461571 , 0.39665488, 0.53647101],
        [0.38461805, 0.9712553 , 0.41469052, 0.28118047]]])